/*
 * Which DSH session is a Feishu chat talking to — and what happens when that
 * changes while the chat's own turn is still running.
 *
 * Two rules are pinned here.
 *
 * 1. A chat can be repointed from inside its own turn: the `reset` tool called
 *    on the chat that is running it, `/new`, `/s`. Disposing that agent from
 *    inside its own turn kills the loop executing the tool call, so the swap is
 *    PARKED in deferredSwaps and retried once the turn's capture is gone. A
 *    turn already past its own ceiling can never settle (a step waiting on a
 *    tool result that will never arrive), so the escape hatch detaches the
 *    session WITHOUT awaiting dispose().
 *
 * 2. `agents.resume` must be handed `agentOptions`. The deployment persona
 *    references {{model}}, which dsh-agent-loop resolves from `agent.options`;
 *    a resume that omits it dies at step/start with
 *    `prompt variable "{{model}}" has no value`.
 *
 * The code under test is sliced out of host.js at run time — edit the plugin
 * and this suite changes with it. Nothing here is a copy of the plugin.
 *
 * Run from anywhere: node tests/test-resume.cjs  (or an absolute path to it)
 */
const fs = require('fs')
const path = require('path')

const src = fs.readFileSync(path.join(__dirname, '..', 'lib', 'bot.js'), 'utf8')

/**
 * The verbatim region of host.js between two markers, both inclusive.
 * With no end marker, up to the end of that line. A missing marker is a hard
 * error naming the marker — never a silent skip.
 */
function slice(startMarker, endMarker) {
  const a = src.indexOf(startMarker)
  if (a === -1) throw new Error('missing start marker in host.js: ' + JSON.stringify(startMarker))
  if (endMarker === undefined) {
    const end = src.indexOf('\n', a)
    return src.slice(a, end === -1 ? src.length : end)
  }
  const b = src.indexOf(endMarker, a)
  if (b === -1) {
    throw new Error('missing end marker in host.js: ' + JSON.stringify(endMarker) + ' after ' + JSON.stringify(startMarker))
  }
  return src.slice(a, b + endMarker.length)
}

const S = {
  maxRemembered: slice('const MAX_REMEMBERED_SESSIONS = '),
  describeError: slice('    function describeError(error) {', "      return error.name === undefined ? message : error.name + ': ' + message\n    }"),
  sessionIdFor: slice('    function sessionIdFor(chatId, generation) {', "      return 'feishu-' + safe + (generation > 0 ? '-g' + generation : '')\n    }"),
  rememberedSessions: slice('    function rememberedSessions(entry) {', '      return entry.sessions\n    }'),
  rememberSession: slice('    function rememberSession(entry, id) {', '      if (entry.sessions.length > MAX_REMEMBERED_SESSIONS) entry.sessions.length = MAX_REMEMBERED_SESSIONS\n    }'),
  effectiveTimeout: slice('    function effectiveTimeout() {', "      return typeof config.timeoutMs === 'number' && config.timeoutMs > 0 ? config.timeoutMs : DEFAULTS.timeoutMs\n    }"),
  currentAgentOptions: slice('    function currentAgentOptions() {', '      if (selection.reasoningEffort !== undefined) options.reasoningEffort = selection.reasoningEffort\n      return options\n    }'),
  withSessionSwap: slice('    async function withSessionSwap(chatId, entry, apply) {', '      return apply()\n    }'),
  restartChatSession: slice('    async function restartChatSession(chatId, entry) {', '        entry.sessionId = sessionIdFor(chatId, entry.generation)\n        return entry.sessionId\n      })\n    }'),
  switchChatSession: slice('    async function switchChatSession(chatId, entry, targetId) {', '        entry.sessionId = targetId\n        return entry.sessionId\n      })\n    }'),
  drainDeferredSwap: slice('    async function drainDeferredSwap(chatId, entry) {', "      log('deferred swap applied chat=' + chatId + ' session=' + entry.sessionId)\n    }"),
  acquireAgent: slice('    async function acquireAgent(entry, displayName) {', '      return createAgent(entry, displayName)\n    }'),
}

/* The generated harness lives beside this file, so the suite is relocatable. */
const SCRATCH = path.join(__dirname, '.scratch')
fs.mkdirSync(SCRATCH, { recursive: true })
const HARNESS = path.join(SCRATCH, 'resume-under-test.cjs')

const prelude = `
/* Generated by tests/test-resume.cjs — the verbatim regions of host.js under
 * test, plus the stub globals standing in for the rest of the plugin. */

${S.maxRemembered}

/* Ambient state the slices close over. */
let config = { timeoutMs: 300000 }
const DEFAULTS = { timeoutMs: 300000, workspacePath: '/d', transport: 'ws' }

/* Captured output, so "it was logged" has an answer. */
const logged = []
function log() { logged.push(Array.prototype.join.call(arguments, ' ')) }

/* The service registry, filled in by the suite per scenario. */
const svcTable = {}
function svc(name) {
  if (svcTable[name] === undefined) throw new Error('missing service ' + name)
  return svcTable[name]
}

const liveHandles = new Map()
const deferredSwaps = new Map()
const captures = new Map()
const saved = { count: 0 }
async function saveState() { saved.count += 1 }

let createAgentCalls = 0
async function createAgent(entry) { createAgentCalls += 1; return { created: entry.sessionId } }
function mountSetup(presetId) { return async function () { return presetId } }
function seedUsage() {}

${S.describeError}

${S.sessionIdFor}

${S.rememberedSessions}

${S.rememberSession}

${S.effectiveTimeout}

${S.currentAgentOptions}

${S.withSessionSwap}

${S.restartChatSession}

${S.switchChatSession}

${S.drainDeferredSwap}

${S.acquireAgent}

module.exports = {
  MAX_REMEMBERED_SESSIONS, rememberedSessions, rememberSession, currentAgentOptions, withSessionSwap,
  restartChatSession, switchChatSession, drainDeferredSwap, acquireAgent,
  liveHandles, deferredSwaps, captures, svcTable, logged, saved,
  createAgentCalls: function () { return createAgentCalls },
}
`
fs.writeFileSync(HARNESS, prelude)
const M = require(HARNESS)

let failures = 0
function check(name, ok, detail) {
  if (ok) {
    console.log('  ok   ' + name)
  } else {
    failures += 1
    console.log('  FAIL ' + name + (detail === undefined ? '' : '\n       ' + detail))
  }
}
let sectionNo = 0
function section(title) {
  sectionNo += 1
  console.log('\n[' + sectionNo + '] ' + title)
}

const CHAT = 'oc_resume'
/* sessionIdFor('oc_resume', 0 | 1); asserted as literals below. */
const SESSION_0 = 'feishu-oc_resume'
const SESSION_1 = 'feishu-oc_resume-g1'
const TARGET = 'feishu-oc_resume-g7'

function newEntry(over) {
  return Object.assign({ generation: 0, chatType: 'p2p', createdAt: Date.now(), sessionId: SESSION_0, sessions: [] }, over)
}

/** A live agent handle that records how it was disposed. */
function handleFor(id) {
  const handle = {
    agent: { session: { id: id } },
    disposeCalls: 0,
    dispose: async function () { handle.disposeCalls += 1 },
  }
  return handle
}

/** runTurn stamps `startedAt` on the capture for the session it is driving. */
function turnInFlight(sessionId, ageMs) {
  M.captures.set(sessionId, { last: '', sent: '', startedAt: Date.now() - (ageMs === undefined ? 0 : ageMs) })
}

function reset() {
  M.liveHandles.clear()
  M.deferredSwaps.clear()
  M.captures.clear()
  M.logged.length = 0
  M.saved.count = 0
  Object.keys(M.svcTable).forEach(function (name) { delete M.svcTable[name] })
}

function resumeStubs(resumeImpl) {
  M.svcTable.agentDefaultModel = { currentSelection: function () { return { provider: 'deepseek', model: 'deepseek-reasoner' } } }
  M.svcTable.agentPresets = { resolve: async function () { return { id: 'standard' } } }
  M.svcTable.agents = { get: function () { return undefined }, resume: resumeImpl }
}

async function main() {
  /* ---------------------------------------------------------------- *
   * the route a session runs on
   * ---------------------------------------------------------------- */
  section('currentAgentOptions forwards the default route')
  reset()
  M.svcTable.agentDefaultModel = {
    currentSelection: function () { return { provider: 'anthropic', model: 'claude-opus-4-6' } },
  }
  const route = M.currentAgentOptions()
  check(
    'provider+model',
    JSON.stringify(route) === JSON.stringify({ provider: 'anthropic', model: 'claude-opus-4-6' }),
    JSON.stringify(route)
  )

  M.svcTable.agentDefaultModel = {
    currentSelection: function () { return { provider: 'deepseek', model: 'deepseek-reasoner', reasoningEffort: 'high' } },
  }
  const effort = M.currentAgentOptions()
  check('reasoningEffort carried when present', effort.reasoningEffort === 'high', JSON.stringify(effort))

  section('resume carries agentOptions (the {{model}} fix)')
  reset()
  const resumeCalls = []
  resumeStubs(async function (args) {
    resumeCalls.push(args)
    return handleFor(args.resumeSessionId)
  })
  const entryResume = newEntry()
  await M.acquireAgent(entryResume, '飞书机器人')
  check('resume called', resumeCalls.length === 1, 'resume calls=' + resumeCalls.length)
  check(
    'agentOptions present',
    resumeCalls[0] !== undefined && resumeCalls[0].agentOptions !== undefined && typeof resumeCalls[0].agentOptions === 'object',
    JSON.stringify(resumeCalls[0])
  )
  check(
    'model passed through',
    resumeCalls[0] !== undefined && resumeCalls[0].agentOptions !== undefined && resumeCalls[0].agentOptions.model === 'deepseek-reasoner',
    JSON.stringify(resumeCalls[0] === undefined ? undefined : resumeCalls[0].agentOptions)
  )

  /* ---------------------------------------------------------------- *
   * a swap requested from inside the chat's own turn
   * ---------------------------------------------------------------- */
  section("reset from inside the chat's own turn is deferred, not applied")
  reset()
  const entryOwn = newEntry()
  const handleOwn = handleFor(SESSION_0)
  M.liveHandles.set(SESSION_0, handleOwn)
  turnInFlight(SESSION_0, 1000)
  const deferredId = await M.restartChatSession(CHAT, entryOwn)
  check('returns undefined', deferredId === undefined, String(deferredId))
  check('sessionId untouched', entryOwn.sessionId === SESSION_0, entryOwn.sessionId)
  check('generation untouched', entryOwn.generation === 0, String(entryOwn.generation))
  check(
    'handle NOT disposed (would orphan the running tool call)',
    handleOwn.disposeCalls === 0,
    'disposeCalls=' + handleOwn.disposeCalls
  )
  check('parked in deferredSwaps', M.deferredSwaps.has(CHAT) === true && typeof M.deferredSwaps.get(CHAT) === 'function')
  check('handle kept for the later swap', M.liveHandles.get(SESSION_0) === handleOwn)

  section('once the turn settles, the parked swap applies and disposes')
  M.captures.delete(SESSION_0) /* runTurn's finally: the turn is over */
  await M.drainDeferredSwap(CHAT, entryOwn)
  check('generation bumped', entryOwn.generation === 1, String(entryOwn.generation))
  check('new session id', entryOwn.sessionId === SESSION_1, entryOwn.sessionId)
  check('old handle disposed', handleOwn.disposeCalls === 1, 'disposeCalls=' + handleOwn.disposeCalls)
  check('flag cleared', M.deferredSwaps.has(CHAT) === false)
  /* Parking a swap saves nothing; applying one saves exactly once. */
  check('state saved', M.saved.count === 1, 'saves=' + M.saved.count)
  check(
    'old session remembered for /s',
    entryOwn.sessions.length === 1 && entryOwn.sessions[0].id === SESSION_0,
    JSON.stringify(entryOwn.sessions.map(function (s) { return s.id }))
  )

  section('a still-busy chat stays parked (retried, never lost)')
  reset()
  const entryBusy = newEntry()
  const handleBusy = handleFor(SESSION_0)
  M.liveHandles.set(SESSION_0, handleBusy)
  turnInFlight(SESSION_0, 0)
  await M.restartChatSession(CHAT, entryBusy)
  await M.drainDeferredSwap(CHAT, entryBusy) /* still inside the ceiling */
  check('still parked while busy', M.deferredSwaps.has(CHAT) === true)
  check('sessionId still original', entryBusy.sessionId === SESSION_0, entryBusy.sessionId)
  M.captures.delete(SESSION_0) /* the turn ends */
  await M.drainDeferredSwap(CHAT, entryBusy) /* the retry */
  check(
    'applies after the turn ends',
    entryBusy.sessionId === SESSION_1 && entryBusy.generation === 1,
    JSON.stringify({ sessionId: entryBusy.sessionId, generation: entryBusy.generation })
  )

  section('an unparked chat drains as a no-op')
  reset()
  const entryIdle = newEntry()
  const idleBefore = JSON.stringify(entryIdle)
  await M.drainDeferredSwap(CHAT, entryIdle)
  check(
    'nothing changed',
    JSON.stringify(entryIdle) === idleBefore && M.saved.count === 0 && M.liveHandles.size === 0,
    JSON.stringify(entryIdle)
  )

  section('an ordinary /new still applies immediately')
  reset()
  const entryNew = newEntry()
  const handleNew = handleFor(SESSION_0)
  M.liveHandles.set(SESSION_0, handleNew)
  const newId = await M.restartChatSession(CHAT, entryNew)
  check('returns the new id', newId === SESSION_1, String(newId))
  check('new session id', entryNew.sessionId === SESSION_1, entryNew.sessionId)
  check('disposed immediately', handleNew.disposeCalls === 1, 'disposeCalls=' + handleNew.disposeCalls)
  check(
    'previous session remembered',
    entryNew.sessions.length === 1 && entryNew.sessions[0].id === SESSION_0,
    JSON.stringify(entryNew.sessions.map(function (s) { return s.id }))
  )

  section('a failed resume still falls back to a fresh session')
  reset()
  resumeStubs(async function () { throw new Error('session log missing') })
  const createCallsBefore = M.createAgentCalls()
  const entryBroken = newEntry()
  await M.acquireAgent(entryBroken, '飞书机器人')
  check(
    'createAgent used as fallback',
    M.createAgentCalls() === createCallsBefore + 1 && M.logged.some(function (line) { return line.indexOf('resume failed for ' + SESSION_0) !== -1 }),
    'createAgentCalls=' + M.createAgentCalls() + ' logged=' + JSON.stringify(M.logged)
  )

  /* ---------------------------------------------------------------- *
   * the turn that can never settle
   * ---------------------------------------------------------------- */
  section('escape hatch: a turn past its ceiling is swapped out, not waited on')
  reset()
  const entryStuck = newEntry()
  let stuckDisposes = 0
  const handleStuck = {
    agent: { session: { id: SESSION_0 } },
    dispose: function () { stuckDisposes += 1; return new Promise(function () {}) },
  }
  M.liveHandles.set(SESSION_0, handleStuck)
  turnInFlight(SESSION_0, 600000) /* ten minutes into a five-minute ceiling */
  const TIMEOUT = 'TIMED OUT: the swap awaited a dispose() that never settles'
  const raced = await Promise.race([
    M.restartChatSession(CHAT, entryStuck),
    new Promise(function (resolve) { setTimeout(function () { resolve(TIMEOUT) }, 250) }),
  ])
  check('returns the new id (swapped, not deferred)', raced === SESSION_1, String(raced))
  check('did NOT await the never-resolving dispose()', raced !== TIMEOUT, String(raced))
  check('dispose() was still invoked', stuckDisposes === 1, 'disposeCalls=' + stuckDisposes)
  check('new session id', entryStuck.sessionId === SESSION_1, entryStuck.sessionId)
  check('stale capture cleared', M.captures.has(SESSION_0) === false)
  check('not parked as deferred', M.deferredSwaps.has(CHAT) === false)
  check(
    'logged as forced',
    M.logged.some(function (line) { return line.indexOf('session swap forced') !== -1 }),
    JSON.stringify(M.logged)
  )

  section('a fresh turn is still deferred (escape hatch must not fire early)')
  reset()
  const entryFresh = newEntry()
  const handleFresh = handleFor(SESSION_0)
  M.liveHandles.set(SESSION_0, handleFresh)
  turnInFlight(SESSION_0, 1000) /* one second into the five-minute ceiling */
  const freshId = await M.restartChatSession(CHAT, entryFresh)
  check('deferred', freshId === undefined && M.deferredSwaps.has(CHAT) === true, String(freshId))
  check(
    'sessionId untouched',
    entryFresh.sessionId === SESSION_0 && handleFresh.disposeCalls === 0,
    entryFresh.sessionId + ' disposeCalls=' + handleFresh.disposeCalls
  )

  /* ---------------------------------------------------------------- *
   * pointing at a session that already exists
   * ---------------------------------------------------------------- */
  section('switching to an existing session repoints without bumping generation')
  reset()
  const entrySwitch = newEntry()
  const handleSwitch = handleFor(SESSION_0)
  M.liveHandles.set(SESSION_0, handleSwitch)
  const switchedId = await M.switchChatSession(CHAT, entrySwitch, TARGET)
  check('returns the target id', switchedId === TARGET, String(switchedId))
  check('sessionId is the target', entrySwitch.sessionId === TARGET, entrySwitch.sessionId)
  check('generation untouched (not a new session)', entrySwitch.generation === 0, String(entrySwitch.generation))
  check('old handle disposed', handleSwitch.disposeCalls === 1, 'disposeCalls=' + handleSwitch.disposeCalls)
  check(
    'previous session remembered',
    entrySwitch.sessions.length === 1 && entrySwitch.sessions[0].id === SESSION_0,
    JSON.stringify(entrySwitch.sessions.map(function (s) { return s.id }))
  )

  section('switching to the session already bound is a no-op')
  reset()
  const entrySame = newEntry({ sessions: [{ id: SESSION_0, at: 1 }] })
  const handleSame = handleFor(SESSION_0)
  M.liveHandles.set(SESSION_0, handleSame)
  const sameId = await M.switchChatSession(CHAT, entrySame, SESSION_0)
  check('returns it unchanged', sameId === SESSION_0, String(sameId))
  check(
    'nothing remembered twice',
    entrySame.sessions.length === 1 && entrySame.sessions.filter(function (s) { return s.id === SESSION_0 }).length === 1,
    JSON.stringify(entrySame.sessions)
  )

  /* ---------------------------------------------------------------- *
   * the remembered-session list behind /s
   * ---------------------------------------------------------------- */
  section('rememberSession dedupes, fronts, and caps')
  reset()
  const entryList = { sessionId: SESSION_0, sessions: [] }
  for (let i = 0; i < 25; i += 1) M.rememberSession(entryList, 'feishu-s' + i)
  check(
    'capped at MAX_REMEMBERED_SESSIONS',
    entryList.sessions.length === M.MAX_REMEMBERED_SESSIONS,
    'length=' + entryList.sessions.length + ' cap=' + M.MAX_REMEMBERED_SESSIONS
  )
  check('most recent first', entryList.sessions[0].id === 'feishu-s24', entryList.sessions[0].id)
  M.rememberSession(entryList, 'feishu-s10')
  check('re-remembering moves to front', entryList.sessions[0].id === 'feishu-s10', entryList.sessions[0].id)
  check(
    'no duplicate',
    entryList.sessions.filter(function (s) { return s.id === 'feishu-s10' }).length === 1 && entryList.sessions.length === M.MAX_REMEMBERED_SESSIONS,
    JSON.stringify(entryList.sessions.map(function (s) { return s.id }))
  )
  const listLength = entryList.sessions.length
  M.rememberSession(entryList, '')
  check('empty id ignored', entryList.sessions.length === listLength, 'length=' + entryList.sessions.length)

  console.log('\n' + (failures === 0 ? 'ALL CHECKS PASSED' : failures + ' FAILED'))
  process.exit(failures === 0 ? 0 : 1)
}

main().catch(function (error) {
  console.error('harness error: ' + (error && error.stack ? error.stack : error))
  process.exit(2)
})
