/*
 * config.json round-tripping: only the operator's real choices are persisted.
 *
 * saveConfig() writes explicitConfig(), which keeps ONLY the values that differ
 * from the shipped DEFAULTS. Writing the MERGED config instead — which is what
 * host.js used to do — freezes today's defaults into the file forever, so a
 * later change to DEFAULTS can never reach an existing installation. That is
 * not hypothetical: a 15-minute `timeoutMs` default got snapshotted into
 * config.json that way and quietly overrode the 5-minute replacement.
 *
 * The code under test — DEFAULTS itself, sameConfigValue and explicitConfig —
 * is sliced out of host.js at run time, so editing the plugin changes the
 * result of this suite. Nothing here is a copy of the plugin.
 *
 * Run from anywhere: node tests/test-config.cjs  (or an absolute path to it)
 */
const fs = require('fs')
const path = require('path')

const src = fs.readFileSync(path.join(__dirname, '..', 'lib', 'bot.js'), 'utf8')

/**
 * The verbatim region of host.js between two markers, both inclusive.
 * With no end marker, up to the end of that line. A missing marker is a hard
 * error naming the marker — never a silent skip.
 */
function slice(startMarker, endMarker) {
  const a = src.indexOf(startMarker)
  if (a === -1) throw new Error('missing start marker in host.js: ' + JSON.stringify(startMarker))
  if (endMarker === undefined) {
    const end = src.indexOf('\n', a)
    return src.slice(a, end === -1 ? src.length : end)
  }
  const b = src.indexOf(endMarker, a)
  if (b === -1) {
    throw new Error('missing end marker in host.js: ' + JSON.stringify(endMarker) + ' after ' + JSON.stringify(startMarker))
  }
  return src.slice(a, b + endMarker.length)
}

const S = {
  defaults: slice('const DEFAULTS = {', '  blockedUserIds: [],\n}'),
  j: slice('    function j(value) {', '        return String(value)\n      }\n    }'),
  sameConfigValue: slice('    function sameConfigValue(a, b) {', '      if (Array.isArray(a) || Array.isArray(b)) return j(a) === j(b)\n      return false\n    }'),
  explicitConfig: slice('    function explicitConfig() {', '        if (!sameConfigValue(config[key], DEFAULTS[key])) out[key] = config[key]\n      }\n      return out\n    }'),
}

/* The generated harness lives beside this file, so the suite is relocatable. */
const SCRATCH = path.join(__dirname, '.scratch')
fs.mkdirSync(SCRATCH, { recursive: true })
const HARNESS = path.join(SCRATCH, 'config-under-test.cjs')

const prelude = `
/* Generated by tests/test-config.cjs — the verbatim regions of host.js under
 * test, plus the module-level state the operator's config lives in. */

${S.defaults}

/* What loadConfig() builds: DEFAULTS merged under the file's contents. */
let config = Object.assign({}, DEFAULTS)

${S.j}

${S.sameConfigValue}

${S.explicitConfig}

module.exports = {
  DEFAULTS, explicitConfig, sameConfigValue,
  peekConfig: function () { return config },
  set: function (over) {
    config = Object.assign({}, DEFAULTS, over || {})
    return config
  },
}
`
fs.writeFileSync(HARNESS, prelude)
const M = require(HARNESS)

let failures = 0
function check(name, ok, detail) {
  if (ok) {
    console.log('  ok   ' + name)
  } else {
    failures += 1
    console.log('  FAIL ' + name + (detail === undefined ? '' : '\n       ' + detail))
  }
}
let sectionNo = 0
function section(title) {
  sectionNo += 1
  console.log('\n[' + sectionNo + '] ' + title)
}

/* ---------------------------------------------------------------- *
 * only the operator's choices survive a save
 * ---------------------------------------------------------------- */
section('a value equal to the default is NOT written back')
M.set({})
const untouched = M.explicitConfig()
check('empty object', Object.keys(untouched).length === 0, JSON.stringify(untouched))

section('this is the exact bug: a stamped-in default must not survive')
M.set({ timeoutMs: 900000 })
check(
  '900000 kept (operator pinned it explicitly)',
  M.explicitConfig().timeoutMs === 900000,
  JSON.stringify(M.explicitConfig())
)
/* host.js ships DEFAULTS.timeoutMs = 300000; a value the old save path stamped
 * into config.json must be dropped again so a later default change reaches it. */
M.set({ timeoutMs: 300000 })
check(
  '300000 dropped (follows the code default)',
  M.explicitConfig().timeoutMs === undefined,
  'DEFAULTS.timeoutMs=' + JSON.stringify(M.DEFAULTS.timeoutMs) + ' explicit=' + JSON.stringify(M.explicitConfig())
)

section('real choices are preserved')
/* A workspace that simply is not the shipped default; nothing is read from it. */
const OTHER_WORKSPACE = '/workspaces/feishu-config-suite'
M.set({
  appId: 'cli_a1b2c3d4',
  appSecret: 's3cret-value',
  workspacePath: OTHER_WORKSPACE,
  bridgeToken: 'tok-9f8e7d',
})
const chosen = M.explicitConfig()
check('appId', chosen.appId === 'cli_a1b2c3d4', JSON.stringify(chosen))
check('appSecret', chosen.appSecret === 's3cret-value', JSON.stringify(chosen))
check('workspacePath (differs from default)', chosen.workspacePath === OTHER_WORKSPACE, JSON.stringify(chosen.workspacePath))
check('bridgeToken (no default at all)', chosen.bridgeToken === 'tok-9f8e7d', JSON.stringify(chosen.bridgeToken))
check('transport omitted', chosen.transport === undefined, JSON.stringify(chosen))

/* ---------------------------------------------------------------- *
 * the two list fields
 * ---------------------------------------------------------------- */
section('arrays compare structurally, not by identity')
M.set({ allowedChatIds: [] })
const emptyList = M.explicitConfig()
check(
  'empty array equals default -> dropped',
  emptyList.allowedChatIds === undefined && M.peekConfig().allowedChatIds !== M.DEFAULTS.allowedChatIds,
  'explicit=' + JSON.stringify(emptyList)
)
M.set({ allowedChatIds: ['oc_a', 'oc_b'] })
check(
  'non-empty array -> kept',
  JSON.stringify(M.explicitConfig().allowedChatIds) === JSON.stringify(['oc_a', 'oc_b']),
  JSON.stringify(M.explicitConfig())
)
M.set({ blockedUserIds: ['ou_x'] })
check(
  'non-empty array vs empty default -> kept',
  JSON.stringify(M.explicitConfig().blockedUserIds) === JSON.stringify(['ou_x']),
  JSON.stringify(M.explicitConfig())
)

section('sameConfigValue edges')
check('identical strings', M.sameConfigValue('ws', 'ws') === true)
check('different strings', M.sameConfigValue('ws', 'webhook') === false)
check('number vs string', M.sameConfigValue(300000, '300000') === false)
check('undefined vs undefined', M.sameConfigValue(undefined, undefined) === true)
check('undefined vs value', M.sameConfigValue(undefined, 'ws') === false)
check('true vs false', M.sameConfigValue(true, false) === false)
check('two empty arrays', M.sameConfigValue([], []) === true)
check('array vs non-array', M.sameConfigValue(['a', 'b'], 'a,b') === false)

console.log('\n' + (failures === 0 ? 'ALL CHECKS PASSED' : failures + ' FAILED'))
process.exit(failures === 0 ? 0 : 1)
